config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
   resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
   end
   resources :users, only: [:show, :index, :edit, :update]
   get "home/about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :profile_image, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!,except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  user_path(current_user.id)
end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
    else
        @books = Book.all
        @user = current_user
        render :index
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.new
    @book2 = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
			redirect_to books_path
		end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book was successfully updated."
       redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
			redirect_to books_path
    else
    @book.destroy
    redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :use_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
			redirect_to user_path(@current_user.id)
		end
  end


   def update
  		@user = User.find(params[:id])
  		if @user.update(user_params)
  			flash[:notice] = "User was successfully updated."
  			redirect_to user_path(@user.id)
  		else
  			render :edit
  		end
   end

    private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profile_images_helper.rb
module ProfileImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
      <%= form_with model:@book, url:"/books/#{@book.id}", local: true do |f| %>
      <%= render "layouts/error_messages", book: @book %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %><br>
         <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book"><br>

        <%= link_to "Show", book_path(@book.id) %>
        <%= link_to "Back", books_path %>

      <% end %>

   </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/list', user: @user, book: @book %>

 <div class="col-md-8 offset-md-1">
   <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
           <tr>
             <td>
              <%= link_to user_path(book.user.id) do %>
          　<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %>
          　<% end %>
          　 </td>
          　 <td>
            <%= link_to book_path(book.id) do %>
              <p>title : <%= book.title %></p>
            <% end %>
             </td>
             <td>
              <p>opinion : <%= book.body %></p>
             </td>
             <td>
              <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                ♥<%= book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
          <% end %>
             </td>
             <td>
              <p>コメント数：<%= book.book_comments.count %></p>
             </td>
            </tr>
          <% end %>
        </tbody>
    </table>
   </div>

 </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model:@book, local:true do |f| %>
 <h4>title</h4>
 <%= f.text_field :title %>
 <h4>Opinion</h4>
 <%= f.text_field :body %><br>
 <%= f.submit 'Create Book' %>
 <% end %>
 
 <% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <p>title : <%= book.title %></p>
  <% end %>
  <p>opinion : <%= book.body %></p>
</div>
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
    <div class="profile-container">
      <%= attachment_image_tag @book2.user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %>
      <table class="table table-hover table-inverse">
        <thad>
          <tr>
          <th>name</th>
          <td><%= @book2.user.name %></td>
          </tr>
        </thad>
        <tr>
          <th>introduction</th>
          <td><%= @book2.user.introduction %></td>
        </td>
      </table>
    </div>
  <%= link_to edit_user_path(@book2.user) do %>
    <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
  <% end %>


    <h2>New book</h2>
    <%= form_with model:@book, local:true do |f| %>
    <%= render "layouts/error_messages", book: @book %>
      <h4>Title</h4>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
       <h4>opinion</h4>
          <%= f.text_area :body, class: "col-xs-12 book_body" %>
     <br>
     <div class="form">
       <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
     </div>
    <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
   <table class="table table-hover table-inverse">
        <tbody>
        <tr>
          <td>
          <%= link_to user_path(@book2.user.id) do %>
          <%= attachment_image_tag @book2.user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %>
          <% end %>
          <%= link_to user_path(@book2.user.id) do %>
             <p><%= @book2.user.name %></p>
          <% end %>
          </td>
          <td>
           <%= link_to book_path(@book2.id) do %>
            <p><%= @book2.title %></p>
           <% end %>
           </td>
           <td>
          <p><%= @book2.body %></p>
           </td>
         <td>
          <% if @book2.user == current_user %>
            <%= link_to "Edit" , edit_book_path(@book2), class: "btn-sm btn-success" %>
            <%= link_to "Destroy", book_path(@book2.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn-sm btn-danger" %>
          <% end %>
         </td>
         <td>
            <% if @book2.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(@book2), method: :delete do %>
                ♥<%= @book2.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(@book2), method: :post do %>
                ♡<%= @book2.favorites.count %>
              <% end %>
            </p>
          <% end %>
         </td>
         <td>
           <p>コメント数：<%= @book2.book_comments.count %></p>
         </td>
        </tr>
     </tbody>
    </table>
    <div class="comments">
        <% @book2.book_comments.each do |book_comment| %>
          <p><%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %></p>
          <%= book_comment.user.name %>
          <%= book_comment.comment %>
           <% if book_comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn-sm btn-danger" %>
              </div>
              <% end %>
          <% end %>
    </div>
　 <div class="col-auto">
        <div class="new-comment">
            <%= form_with(model:[@book2, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, size: "80x5", placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
            <% end %>
       </div>
   </div>

 </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


      <h1>Welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!</h1>

    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="mx-auto" style="width: 540px;">
<h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!!</h1>
<p>In<strong><i class="fas fa-book"></i>Bookers</strong>,</p><br>
<p>you can share and exchange your opinions , inpressions ,</p><br>
<p>about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
    <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
   </div>
</div>

app/views/homes/top.html.erb
<h1>welcome to <strong>Bookers</strong>!!</h1>
<p>In<strong>Bookers</strong>,</p><br>
<p>you can share and exchange your opinions , inpressions ,</p><br>
<p>about various books!</p>

      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>

app/views/layouts/_error_messages.html.erb
<% if book.errors.any? %>
  <h2>error</h2>
    <div class = "alert alert-warning">
        <ul>
            <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_error_messages2.html.erb
<% if user.errors.any? %>
  <h2>error</h2>
    <div class = "alert alert-warning">
        <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_list.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
    <div class="profile-container">
      <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %>
      <table class="table table-hover table-inverse">
        <thad>
          <tr>
          <th>name</th>
          <td><%= user.name %></td>
          </tr>
        </thad>
        <tr>
          <th>introduction</th>
          <td><%= user.introduction %></td>
        </td>
      </table>
    </div>
  <%= link_to edit_user_path(user) do %>
    <i class="btn btn-outline-secondary btn-block fas fa-user-cog"></i>
  <% end %>


    <h2>New book</h2>
    <%= form_with model:@book, local:true do |f| %>
    <%= render "layouts/error_messages", book: book %>
      <h4>Title</h4>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
       <h4>opinion</h4>
          <%= f.text_area :body, class: "col-xs-12 book_body" %>
     <br>
     <div class="form">
       <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
     </div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand p-3" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          <p class="text-white bg-dark"><%= flash[:notice] %></p>
           <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home nav-link text-light">Home</i>
              <% end %>
            </li>
            <li>
             <%= link_to users_path do %>
              <i class="fas fa-users nav-link text-light">Users</i>
             <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
              <i class="fas fa-book-open nav-link text-light">Books</i>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                 <i class="fas fa-sign-out-alt nav-link text-light">logout</i>
              <% end %>
            </li>
            <% else %>
             <li>
            <%= link_to root_path do %>
              <i class="fas fa-home nav-link text-light"> Home</i>
            <% end %>
            </li>
            <li>
            <%= link_to home_about_path do %>
               <i class="fas fa-link nav-link text-light" > About</i>
            <% end %>
            </li>
            <li>
             <%= link_to new_user_registration_path do %>
             <i class="fas fa-user-plus nav-link text-light"> sign up</i>
             <% end %>
            </li>
            <li>
               <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt nav-link text-light"> login</i>
              <% end %>
            </li>
            <% end %>
           </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    	    	<p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User Info</h2>
        <%= form_with model:@user, local: true do |f| %>
        <%= render "layouts/error_messages2", user: @user %>
          <h4>Name</h4>
          <%= f.text_field :name %>

          <h4>Image</h4>
          <%= f.attachment_field :profile_image %>

          <h4>Introduction</h4>
          <%= f.text_area :introduction %><br>
          <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User"><br>

        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/list', user: @user, book: @book %>

   <div class="col-md-8 offset-md-1">
     <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <h2>Users</h2>
          <% @users.each do |user| %>
           <tr>
            <td>
            <p>
                <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %>
            </p>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id)  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
   </div>

  </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/list', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
           <% @books.each do |book| %>
           <tr>
             <td>
            <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format:'jpg', fallback: "no_image.jpg" %>
            <% end %>
            </td>
            <td>
            <%= link_to book_path(book.id) do %>
             <p><%= book.title %></p>
            <% end %>
            </td>
            <td><p><%= book.body %></p></td>
            <td>
                <p>コメント数：<%= book.book_comments.count %></p>
            </td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>

  </div>
</div>